name: smar_bank_app
description: Aplicação Smart Bank

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.2
  nb_utils: ^4.0.6
  google_fonts: 2.0.0
  animations: ^2.0.0
  intl: ^0.17.0
  http: ^0.13.0
  firebase_core: ^1.0.1
  firebase_crashlytics: ^1.0.0
  google_mobile_ads: ^0.11.0+2
  html: ^0.15.0
  share: ^2.0.1
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  flutter_vector_icons: ^1.0.0
  package_info: ^2.0.0

  simple_animations: ^3.0.1
  snaplist: 0.1.8
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_slidable: 0.5.7
  flutter_staggered_grid_view: ^0.3.4
  flutter_staggered_animations: 1.0.0

  google_sign_in: ^5.0.0
  geolocator: ^7.0.1
  geocoder: 0.2.1
  google_maps_flutter: ^2.0.1
  razorpay_flutter: ^1.2.5
  signature: ^4.0.0-nullsafety
  liquid_swipe: ^2.0.0
  lipsum: 1.0.1
  flutter_colorpicker: ^0.3.5
  clippy_flutter: 1.1.1
  flutter_tags: ^0.4.8
  video_player: ^2.0.2
  charts_flutter: ^0.10.0
  flutter_reaction_button: ^1.0.7+3
  lottie: ^1.0.1
  showcaseview: ^0.1.6
  cached_network_image: ^2.3.1
  local_auth: ^1.1.0
  dots_indicator: ^2.0.0
  flutter_banner: ^1.0.1
  image_picker: ^0.7.2
  file_picker: ^3.0.0
  flutter_local_notifications: ^5.0.0-nullsafety.1
  flutter_rating_bar: ^4.0.0
  percent_indicator: 2.1.9+1
  carousel_slider:  4.0.0-nullsafety.0

  geohash: ^0.2.1

  #Dimond kit
  sleek_circular_slider: ^2.0.0
  sliding_up_panel: ^1.0.2

  #clustering_google_maps: ^0.1.2
  #image_picker_gallery_camera: 0.1.6

  flutter_localizations:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #- assets
    - images/banking/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
