// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartBank.Infra.Data.Repository.Context;

namespace SmartBank.Infra.Data.Repository.Migrations
{
    [DbContext(typeof(SmartBankContext))]
    [Migration("20210318193439_Migration_v0.0.0.0001")]
    partial class Migration_v0000001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("SmartBank.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Atualizado")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Cadastro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 18, 16, 34, 38, 735, DateTimeKind.Local).AddTicks(9427))
                        .HasColumnName("data_atualizacao");

                    b.Property<string>("Cnh")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("cnh");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<int>("Escolaridade")
                        .HasColumnType("integer")
                        .HasColumnName("escolaridade");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeMae")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nome_mae");

                    b.Property<string>("NomePai")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("nome_pai");

                    b.Property<string>("Rg")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("rg");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer")
                        .HasColumnName("sexo");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("SmartBank.Domain.Entities.Cliente", b =>
                {
                    b.OwnsOne("SmartBank.Domain.ValuesObject.ClienteEmpresaValueObject", "EmpresaTrabalho", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Cnpj")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("empresa_trabalho_cnpj");

                            b1.Property<string>("NomeFantasia")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("empresa_trabalho_nome_fantasia");

                            b1.Property<string>("RazaoSocial")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("empresa_trabalho_razao_social");

                            b1.HasKey("ClienteId");

                            b1.ToTable("cliente");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");

                            b1.OwnsOne("SmartBank.Domain.ValuesObject.ContatoValueObject", "Contato", b2 =>
                                {
                                    b2.Property<Guid>("ClienteEmpresaValueObjectClienteId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Email")
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("empresa_trabalho_email");

                                    b2.Property<string>("TelefoneCelular")
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("empresa_trabalho_celular");

                                    b2.Property<string>("TelefoneFixo")
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("empresa_trabalho_telefone");

                                    b2.HasKey("ClienteEmpresaValueObjectClienteId");

                                    b2.ToTable("cliente");

                                    b2.WithOwner()
                                        .HasForeignKey("ClienteEmpresaValueObjectClienteId");
                                });

                            b1.OwnsOne("SmartBank.Domain.ValuesObject.EnderecoValueObject", "Endereco", b2 =>
                                {
                                    b2.Property<Guid>("ClienteEmpresaValueObjectClienteId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Bairro")
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("empresa_trabalho_bairro");

                                    b2.Property<string>("Cep")
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("empresa_trabalho_cep");

                                    b2.Property<string>("Cidade")
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("empresa_trabalho_cidade");

                                    b2.Property<int>("CodigoIBGE")
                                        .HasMaxLength(256)
                                        .HasColumnType("integer")
                                        .HasColumnName("empresa_trabalho_cidade_ibge");

                                    b2.Property<string>("Complemento")
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("empresa_trabalho_endereco_complemento");

                                    b2.Property<string>("Logradouro")
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("empresa_trabalho_endereco_logradouro");

                                    b2.Property<string>("Numero")
                                        .HasMaxLength(256)
                                        .HasColumnType("character varying(256)")
                                        .HasColumnName("empresa_trabalho_endereco_numero");

                                    b2.HasKey("ClienteEmpresaValueObjectClienteId");

                                    b2.ToTable("cliente");

                                    b2.WithOwner()
                                        .HasForeignKey("ClienteEmpresaValueObjectClienteId");
                                });

                            b1.Navigation("Contato");

                            b1.Navigation("Endereco");
                        });

                    b.OwnsOne("SmartBank.Domain.ValuesObject.ContatoValueObject", "Contato", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("email");

                            b1.Property<string>("TelefoneCelular")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("telelefone_celular");

                            b1.Property<string>("TelefoneFixo")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("telefone_fixo");

                            b1.HasKey("ClienteId");

                            b1.ToTable("cliente");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.OwnsOne("SmartBank.Domain.ValuesObject.EnderecoValueObject", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("ClienteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bairro")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("endereco_bairro");

                            b1.Property<string>("Cep")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("endereco_cep");

                            b1.Property<string>("Cidade")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("endereco_cidade");

                            b1.Property<int>("CodigoIBGE")
                                .HasColumnType("integer")
                                .HasColumnName("cidade_codigo_ibge");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("endreco_complemento");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("endreco_logradouro");

                            b1.Property<string>("Numero")
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("endreco_numero");

                            b1.HasKey("ClienteId");

                            b1.ToTable("cliente");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Contato");

                    b.Navigation("EmpresaTrabalho");

                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
